### ISSUE TITLE
Multiple Inputs

### ISSUE THREAD

**Issue by collinz1** [danwalkeruk/fortigate2csv#2]
Dan, me again :)
Wondering if its possible to be able to pass multiple input items as the same time, for example "-i <multiple>", providing the ability to log on once but pull back different parts of the config?

**Comment by danwalkeruk** [comment]
Hi @collinz1,

The issue with multiple objects is it would need to output multiple CSVs, so you'd also have to pass the same number of arguments to the `-o`, or accept defaults (that could overwrite files) - it would need some logic.

What is it you are trying to do? Are you trying to get everything you need from a single command, so you could (for example) have a single CRON entry that exports everything for a given VDOM with only one CRON entry?

**Comment by collinz1** [comment]
Good point, im personally not too fussed about the output being in seperate CSV files, but thats just me :).
What i'm trying to achieve is to have one command run, that would print the output of various inputs.  For example creating a new item ("multiple" for example) that actually runs a number of the "args.item's" as part of it (policy,address,interface for example). A CRON entry is probably what i'm talking about by the sounds of things.

**Comment by danwalkeruk** [comment]
> Good point, im personally not too fussed about the output being in seperate CSV files, but thats just me :).

I think ideally you need separate CSVs, because different objects have different headers in the top row. CSVs are obviously simple files (unlike XLS or XLSX) so they don't support tabs or sheets etc.

I can take a look at making `-i` accept comma separated object names for outputting, and make it so that if you use multiple items as part of the `-i` argument, it ignores any `-o` and perhaps uses a nicer naming convention for the output files.

**Comment by collinz1** [comment]
That would be great, fair point re the headers.
output file naming using <vdom>_<item> would possibly work well for output files, which would save overwritting of files when working with different vdoms.

**Comment by collinz1** [comment]
> That would be great, fair point re the headers.
> output file naming using _ would possibly work well for output files, which would save overwritting of files when working with different vdoms.

try that again
*using "VDOM_ITEM.csv" would possibly work well for output files, which would save overwritting of files when working with different vdoms.

**Comment by danwalkeruk** [comment]
> > That would be great, fair point re the headers.
> > output file naming using _ would possibly work well for output files, which would save overwritting of files when working with different vdoms.
> 
> try that again
> *using "VDOM_ITEM.csv" would possibly work well for output files, which would save overwritting of files when working with different vdoms.

I'll take a look soon at implementing something that should work for you.

Also FYI, you can edit your previous comments :)

**Comment by danwalkeruk** [comment]
Closing this as it's an old issue, and my preference has changed to keep it simple. I use the script to redirect the output to different locations, it should be trivial to tweak it as needed.
